### ISSUE TITLE
Issue with "Filtered" function

### ISSUE THREAD

**Issue by valentinthoss** [KevinW1998/nightjetter#2]
The OffersFiltered function does not seem to work properly anymore, maybe because the output of nightjet.com has changed?

Thanks for your help :) Really appreciate your code!

```
PyError ($(Expr(:escape, :(ccall(#= /Users/XXX/.julia/packages/PyCall/ilqDX/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
TypeError("string indices must be integers, not 'str'")
  File "/Users/XXX/./main.py", line 122, in findOffersFiltered
    if "Kein Storno" in offer["prodGroupLabels"]:
```

**Comment by KevinW1998** [comment]
I'll have a look at it. With what parameters did you call the function?

**Comment by valentinthoss** [comment]
Sorry, the resulting error was caused by a change in the code that i actually made myself... Very stupid of me...
