### ISSUE TITLE
What are the codes for the discount cards?

### ISSUE THREAD

**Issue by valentinthoss** [KevinW1998/nightjetter#6]
Is there a list of the id's of all the discount cards? In the code only a few examples are given. I would e.g. be interested in the Interrail Pass one. Thank you!

**Comment by KevinW1998** [comment]
I fetched them from the ÖBB website. Might be able to fetch all codes.

**Comment by KevinW1998** [comment]
I quickly checked: The global Interrail pass has code: 2391

If you want to find more, please check the nightjet website: https://www.nightjet.com/de/ticket-buchen

Go to the network tab of your Browser. Select the discount cards where you want to have the internal codes for. Check for the network request "https://www.nightjet.com/nj-booking-ocp/offer/get" and check the json result. Something like:

```json
{"njFrom":8011102,"njDep":1716744060000,"njTo":8103000,"maxChanges":0,"filter":{"njTrain":"NJ 457","njDeparture":1716744060000},"objects":[{"type":"person","gender":"male","birthDate":"1994-05-25","cards":[2391]}],"relations":[],"lang":"de"}
```

**Comment by valentinthoss** [comment]
Thank you!
